/* eslint-disable object-curly-spacing */
/* eslint-disable no-unused-vars */
const {Photo} = require('../models');

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await Photo.bulkCreate([
      {
        title: 'Фото 1',
        img: 'https://drive.google.com/file/d/1oa5KCE9RDpn_oRrn24B0vNlLa80blZ5S/view?usp=drive_link',
        description: 'один',
        albumId: 1,
        userId: 1,
      },
      {
        title: 'Фото 2',
        img: 'https://drive.google.com/file/d/1eb61NUFIrwxVWuy2pMKcFxoDy245dtmJ/view?usp=drive_link',
        description: 'два',
        albumId: 1,
        userId: 1,
      },
      {
        title: 'Фото 3',
        img: 'https://drive.google.com/file/d/1OI_laRoOEsdBJYEexqUcIocdknGfD4rt/view?usp=drive_link',
        description: 'три',
        albumId: 1,
        userId: 1,
      },
      {
        title: 'Фото 4',
        img: 'https://drive.google.com/open?id=19QOiR03ho2nVY9MSTRP3X6731r5EPMju&usp=drive_copy',
        description: 'четыре',
        albumId: 1,
        userId: 1,
      },
      {
        title: 'Фото 5',
        img: 'https://drive.google.com/open?id=1lyGUgGiOxQuBBmED3OaEoGdbYk2IjMmj&usp=drive_copy',
        description: 'пять',
        albumId: 1,
        userId: 1,
      },
      {
        title: 'Фото 6',
        img: 'https://drive.google.com/open?id=1Fj0O5MEh-zGJkzB1XHYjK7jwjBSooGTi&usp=drive_copy',
        description: 'шесть',
        albumId: 1,
        userId: 1,
      },
      {
        title: 'Фото 1',
        img: 'https://drive.google.com/file/d/1SeEY5RdQ5aQMXO-lLv-6y9xLwp7DlZfA/view?usp=drive_link',
        description: 'один',
        albumId: 2,
        userId: 1,
      },
      {
        title: 'Фото 2',
        img: 'https://drive.google.com/file/d/1m4R6FdsXAjtngWPo5Hc0Du5O_smuzmS7/view?usp=drive_link',
        description: 'два',
        albumId: 2,
        userId: 1,
      },
      {
        title: 'Фото 3',
        img: 'https://drive.google.com/file/d/1oi_001j4DrtcaR5uO_w9kcJXqoVT2PQJ/view?usp=drive_link',
        description: 'три',
        albumId: 2,
        userId: 1,
      },
      {
        title: 'Фото 4',
        img: 'https://drive.google.com/file/d/1WCIufZUQA5BPlSR3i5Tu4Vz2StYgSlIy/view?usp=drive_link',
        description: 'четыре',
        albumId: 2,
        userId: 1,
      },
      {
        title: 'Фото 5',
        img: 'https://drive.google.com/file/d/1YxKQAUi1kg7fIZoBvVXVmbZF9OZs_TzM/view?usp=drive_link',
        description: 'пять',
        albumId: 2,
        userId: 1,
      },
      {
        title: 'Фото 6',
        img: 'https://drive.google.com/file/d/1Hhl47U2nuPrgYw8jNUW5KREoHPYd7k3g/view?usp=drive_link',
        description: 'шесть',
        albumId: 2,
        userId: 1,
      },
      {
        title: 'Фото 1',
        img: 'https://drive.google.com/file/d/1MQPCzfbxFljvTRAXQzrc0HQp4GAH-B5q/view?usp=drive_link',
        description: 'один',
        albumId: 3,
        userId: 1,
      },
      {
        title: 'Фото 2',
        img: 'https://drive.google.com/file/d/1Ko4xShpDVXMVS3ZR8yNYNXmJOh2uQ1_n/view?usp=drive_link',
        description: 'два',
        albumId: 3,
        userId: 1,
      },
      {
        title: 'Фото 3',
        img: 'https://drive.google.com/file/d/1VBm0vIhJuK5G2gE7KHaGEyFgQUe1eya-/view?usp=drive_link',
        description: 'три',
        albumId: 3,
        userId: 1,
      },
      {
        title: 'Фото 4',
        img: 'https://drive.google.com/file/d/1QRfbXdsO_pYDZ_DRZd9VD0Mm5iwyN7HY/view?usp=drive_link',
        description: 'четыре',
        albumId: 3,
        userId: 1,
      },
      {
        title: 'Фото 5',
        img: 'https://drive.google.com/file/d/1bpoUVHuJTnzaqd3iEwZqVb-MaeP8y_hc/view?usp=drive_link',
        description: 'пять',
        albumId: 3,
        userId: 1,
      },
      {
        title: 'Фото 6',
        img: 'https://drive.google.com/file/d/1SALHg1-R8Vn7iN0iJBczsqUMTg3JyiBT/view?usp=drive_link',
        description: 'шесть',
        albumId: 3,
        userId: 1,
      },
      {
        title: 'Фото 1',
        img: 'https://drive.google.com/file/d/1kaKr0rcPDCF6vCB1XiHoNNuBLTwzhpjd/view?usp=drive_link',
        description: 'один',
        albumId: 4,
        userId: 1,
      },
      {
        title: 'Фото 2',
        img: 'https://drive.google.com/file/d/1cMlQ0eWoiRa-_CTnBJdO-2K8ePfek01x/view?usp=drive_link',
        description: 'два',
        albumId: 4,
        userId: 1,
      },
      {
        title: 'Фото 3',
        img: 'https://drive.google.com/file/d/1N9TM2NL7zZCi29K8jrwb-2AD4K9ujNEA/view?usp=drive_link',
        description: 'три',
        albumId: 4,
        userId: 1,
      },
      {
        title: 'Фото 4',
        img: 'https://drive.google.com/file/d/1ZmNi6QYPhCVywhj2EhE0x_oTL9XZL7wf/view?usp=drive_link',
        description: 'четыре',
        albumId: 4,
        userId: 1,
      },
      {
        title: 'Фото 5',
        img: 'https://drive.google.com/file/d/1dLmkmZpx-5NJQnNb0e6uXtq_bMy8Hxsh/view?usp=drive_link',
        description: 'пять',
        albumId: 4,
        userId: 1,
      },
      {
        title: 'Фото 6',
        img: 'https://drive.google.com/file/d/1fwQGw9UtNRqxJYw-XCyv93_hoQ-dAUs9/view?usp=drive_link',
        description: 'шесть',
        albumId: 4,
        userId: 1,
      },
      {
        title: 'Фото 1',
        img: 'https://drive.google.com/file/d/1cZ4fAAe9LpRiACELDOohXO3YktX-ml0w/view?usp=drive_link',
        description: 'один',
        albumId: 5,
        userId: 1,
      },
      {
        title: 'Фото 2',
        img: 'https://drive.google.com/file/d/1QeMXWbEdXLZtkhtc8SFhtgPDV_DnjhMe/view?usp=drive_link',
        description: 'два',
        albumId: 5,
        userId: 1,
      },
      {
        title: 'Фото 3',
        img: 'https://drive.google.com/file/d/1HegjY1P4gHxrs1CZRJh1kOu2DQajGU-1/view?usp=drive_link',
        description: 'три',
        albumId: 5,
        userId: 1,
      },
      {
        title: 'Фото 4',
        img: 'https://drive.google.com/file/d/1dWn8xcuytWolzwNUTqOAy9vI3bWNjilF/view?usp=drive_link',
        description: 'четыре',
        albumId: 5,
        userId: 1,
      },
      {
        title: 'Фото 5',
        img: 'https://drive.google.com/file/d/1TW5nlDTXZggv91UpCiPl5IuGSi-oF9Xd/view?usp=drive_link',
        description: 'пять',
        albumId: 5,
        userId: 1,
      },
      {
        title: 'Фото 6',
        img: 'https://drive.google.com/file/d/1AhgZVL24WH2Fp7n30CIWSFye0mlAKwyX/view?usp=drive_link',
        description: 'шесть',
        albumId: 5,
        userId: 1,
      },
      {
        title: 'Фото 1',
        img: 'https://drive.google.com/file/d/1TYzrIfZ6Q752PhRKrqze_FHdZxKHxgyk/view?usp=drive_link',
        description: 'один',
        albumId: 6,
        userId: 1,
      },
      {
        title: 'Фото 2',
        img: 'https://drive.google.com/file/d/10BI99Jh6W7XrhJwA6At999zROHT9tsKY/view?usp=drive_link',
        description: 'два',
        albumId: 6,
        userId: 1,
      },
      {
        title: 'Фото 3',
        img: 'https://drive.google.com/file/d/1lA-wcurv0DCWq7mT0lEGBQtn_u5M1B-q/view?usp=drive_link',
        description: 'три',
        albumId: 6,
        userId: 1,
      },
      {
        title: 'Фото 4',
        img: 'https://drive.google.com/file/d/1139GoAs4ZYznI6v2fAG5qcWoZrvDUoo3/view?usp=drive_link',
        description: 'четыре',
        albumId: 6,
        userId: 1,
      },
      {
        title: 'Фото 5',
        img: 'https://drive.google.com/file/d/19d15hgrHUeJWEHtdcachSoJ_lzxJ_p24/view?usp=drive_link',
        description: 'пять',
        albumId: 6,
        userId: 1,
      },
      {
        title: 'Фото 6',
        img: 'https://drive.google.com/file/d/1V4Dx401mQ872EMvFytHAYU7wJwt5-BVd/view?usp=drive_link',
        description: 'шесть',
        albumId: 6,
        userId: 1,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await Photo.destroy({where: {}});
  },
};
